plugin: gcp_compute
zones:
  - us-west1-a
projects:
  - switchbot-from-discordbot
scopes:
  - https://www.googleapis.com/auth/compute
access_token: <your-access-token>
auth_kind: accesstoken
filters: []
hostnames:
  - name