name: Deploy to GCP-VM
 
on:
  push:
    branches:
      - feature-actions
 
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
 
      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: switchbot-from-discordbot
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Ansible
        id: setup_ansible
        run: |
          pip install ansible-core requests google-auth
          ansible-galaxy collection install google.cloud
    
      - name: Setup Ansible inventory
        id: setup_inventory
        run: |
          pwd
          sed -i "s|<your-service-account-file-path>|${{steps.auth.outputs.credentials_file_path}}|" ansible/inventories/bot_container/bot_container.gcp.yaml
          cat ansible/inventories/bot_container/bot_container.gcp.yaml
          cat ${{steps.auth.outputs.credentials_file_path}}
          ansible-inventory --list -i ansible/inventories/bot_container/bot_container.gcp.yaml

      - name: test on VM
        run: |
          gcloud compute ssh khiratsuka-containers@khiratsuka-containers-vm \
            --zone us-west1-a \
            --quiet \
            --command='
              rm ~/.ssh/authorized_keys
            '
      #- name: SSH and Pull Repo in GCP VM
      #  id: git_pull
      #  run: |
      #echo "::set-output name=git_pull_output::$(
      #    gcloud compute ssh user@example-instance \
      #      --zone asia-northeast1-b \
      #      --quiet \
      #      --command='
      #        cd path/to/repository && 
      #        git pull
      #      '
      #  )"